interface BlogPageProps {
  params: { slug: string }
}

export default function BlogPost({ params }: BlogPageProps) {
  const title = decodeURIComponent(params.slug).replace(/-/g, " ")
  return (
    <main className="mx-auto max-w-2xl px-6 py-10">
      <h1 className="mb-4 text-3xl font-semibold tracking-tight text-pretty animate-in fade-in slide-in-from-bottom-2">
        {title}
      </h1>
      <article className="prose prose-invert text-pretty animate-in fade-in-50">
        <p className="text-muted-foreground">
          Start writing your post here. This page is generated by the dynamic route <code>/blog/[slug]</code>. You can
          also create a static folder like <code>app/blog/my-post/page.tsx</code> for a fully custom page.
        </p>
      </article>
    </main>
  )
}
